{
  imports = [
    ../apps/bottles.nix
    ../apps/deadlock-mod-manager.nix
    ../apps/dotnet.nix
    ../apps/flightgear.nix
    ../apps/endless-sky.nix
    ../apps/lutris.nix
    ../apps/mangohud.nix
    ../apps/minesweeper.nix
    ../apps/openttd.nix
    ../apps/osu.nix
    ../apps/prismlauncher.nix
    ../apps/proton.nix
    ../apps/protonup.nix
    ../apps/satisfactory-mod-manager.nix
    ../apps/steam.nix
    ../apps/wine.nix
    ../apps/xivlauncher.nix
  ];
}
